id: P002965
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG12969
  title: བཀའ་བརྒྱུད་བསྟན་སྲུང་རྒྱ་མཚོའི་འཕྲིན་ལས་ཀྱི་ཆོ་ག་དོན་གཉིས་ལྷུན་གྲུབ།
  author: ''
  volumes:
    ba38425847fe415ab6f7f045628d4ecc:
      image_group_id: I1KG13582
      title: ''
      volume_number: 1
      total_pages: 442
      base_file: v001.txt
