id: I721DFFE2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T04:16:36+00:00'
last_modified: '2022-06-07T16:37:18.680842+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12969
  title: བཀའ་བརྒྱུད་བསྟན་སྲུང་རྒྱ་མཚོའི་འཕྲིན་ལས་ཀྱི་ཆོ་ག་དོན་གཉིས་ལྷུན་གྲུབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    899E:
      image_group_id: I1KG13582
      title: ''
      total_pages: 442
      order: 1
      base_file: 899E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
